In [1]:
import pandas as pd

In [151]:
dfs=pd.read_html('https://fbref.com/en/matches/cc5b4244/Manchester-United-Fulham-August-16-2024-Premier-League')

# Match Stat (2)

In [146]:
def process_match_stat_df(df):
    match_stat_df=df
    match_stat_df=match_stat_df.transpose().reset_index(level=1).transpose().reset_index(drop=True)
    match_stat_dict=dict([(match_stat_df.iloc[i*2, 0], [match_stat_df.iloc[i*2+1,0], match_stat_df.iloc[i*2+1,1]]) for i in range(int(len(match_stat_df)/2))])
    match_stat_dict['Possession']=[match_stat_dict['Possession'][0][:-1], match_stat_dict['Possession'][1][:-1]]
    match_stat_dict['passes']=[match_stat_dict['Passing Accuracy'][0].split('\xa0—\xa0')[0].split(' of ')[1], match_stat_dict['Passing Accuracy'][1].split('\xa0—\xa0')[1].split(' of ')[1]]
    match_stat_dict['pass_accuracy']=[match_stat_dict['Passing Accuracy'][0].split('\xa0—\xa0')[1], match_stat_dict['Passing Accuracy'][1].split('\xa0—\xa0')[0]]
    match_stat_dict['pass_accuracy']=[match_stat_dict['pass_accuracy'][0][:-1], match_stat_dict['pass_accuracy'][1][:-1]]
    match_stat_dict['shots']=[match_stat_dict['Shots on Target'][0].split('\xa0—\xa0')[0].split(' of ')[1], match_stat_dict['Shots on Target'][1].split('\xa0—\xa0')[1].split(' of ')[1]]
    match_stat_dict['shots_on_target']=[match_stat_dict['Shots on Target'][0].split('\xa0—\xa0')[0].split(' of ')[0], match_stat_dict['Shots on Target'][1].split('\xa0—\xa0')[1].split(' of ')[0]]
    match_stat_df=pd.DataFrame(match_stat_dict, index=match_stat_df.columns).drop(columns=['Passing Accuracy', 'Shots on Target', 'Saves', 'Cards'])
    match_stat_df.columns=[col.lower().replace(' ','_') for col in match_stat_df.columns.tolist()]
    return match_stat_df
process_match_stat_df(dfs[2])

               possession passes pass_accuracy shots shots_on_target
Manchester Utd         55    524            82    14               5
Fulham                 45    424            78    10               2

# Player Stat (3-8, 10-16)

In [196]:
def process_player_stat_df(df):
    player_df=pd.DataFrame(df)
    cols=[f'player_{col_pair[1]}'.lower() for col_pair in player_df.columns.tolist() if 'Unnamed: ' in col_pair[0]]+[f'{col_pair[0]}_{col_pair[1]}'.replace(' ', '_').lower() for col_pair in player_df.columns.tolist() if 'Unnamed: ' not in col_pair[0]]
    player_df.columns=cols
    player_df=player_df.drop(columns=['player_#', 'player_nation', 'player_pos', 'player_age', 'player_min']).rename(columns={'player_player': 'player'})
    return player_df

In [197]:
process_player_stat_df(dfs[15])

,player,performance_crdy,performance_crdr,performance_2crdy,performance_fls,performance_fld,performance_off,performance_crs,performance_int,performance_tklw,performance_pkwon,performance_pkcon,performance_og,performance_recov,aerial_duels_won,aerial_duels_lost,aerial_duels_won%
0,Rodrigo Muniz,0,0,0,0,1,0,0,1,0,0,0,0,2,4,6,40.0
1,Raúl Jiménez,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,33.3
2,Alex Iwobi,0,0,0,1,0,0,3,0,3,0,0,0,5,0,3,0.0
3,Adama Traoré,0,0,0,3,2,0,1,0,0,0,0,0,6,3,1,75.0
4,Harry Wilson,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,100.0
5,Emile Smith Rowe,0,0,0,0,1,0,1,2,1,0,0,0,3,1,0,100.0
6,Tom Cairney,1,0,0,1,1,0,1,0,0,0,0,0,2,0,1,0.0
7,Saša Lukić,0,0,0,0,1,0,0,1,2,0,0,0,8,0,0,NaN
8,Jay Stansfield,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,NaN
9,Andreas Pereira,1,0,0,2,3,0,12,0,0,0,0,0,9,2,2,50.0
10,Harrison Reed,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,NaN
11,Antonee Robinson,0,0,0,0,0,1,1,2,6,0,0,0,7,2,1,66.7
12,Calvin Bassey,1,0,0,2,0,0,0,0,1,0,0,0,4,1,1,50.0
13,Issa Diop,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,NaN
14,Kenny Tete,0,0,0,0,1,0,2,3,0,0,0,0,6,0,2,0.0
15,Bernd Leno,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,100.0
16,16 Players,3,0,0,10,11,1,21,9,17,0,0,0,53,16,19,45.7

# Shot Stat (17)

In [182]:
def process_shot_stat_df(df):
    shot_stat=pd.DataFrame(df)
    shot_stat.columns=[f'{col_pair[1]}'.lower() for col_pair in shot_stat.columns.tolist() if 'Unnamed: ' in col_pair[0]]+[f'{col_pair[0]}_{col_pair[1]}'.replace(' ', '_').lower() for col_pair in shot_stat.columns.tolist() if 'Unnamed: ' not in col_pair[0]]
    return shot_stat

In [193]:
process_shot_stat_df(dfs[17])

,minute,player,squad,xg,psxg,outcome,distance,body part,notes,sca_1_player,sca_1_event,sca_2_player,sca_2_event
0,8,Adama Traoré,Fulham,0.03,0.00,Off Target,19.0,Right Foot,NaN,Rodrigo Muniz,Pass (Live),Rodrigo Muniz,Take-On
1,13,Kenny Tete,Fulham,0.02,0.28,Saved,31.0,Right Foot,NaN,Andreas Pereira,Pass (Live),Adama Traoré,Pass (Live)
2,14,Rodrigo Muniz,Fulham,0.05,0.00,Blocked,13.0,Head,NaN,Andreas Pereira,Pass (Dead),Kenny Tete,Shot
3,20,Bruno Fernandes,Manchester Utd,0.02,0.00,Off Target,10.0,Left Foot,Volley,Lisandro Martínez,Pass (Live),Harry Maguire,Pass (Live)
4,27,Casemiro,Manchester Utd,0.04,0.00,Off Target,29.0,Right Foot,NaN,Mason Mount,Pass (Live),Kobbie Mainoo,Pass (Live)
5,29,Bruno Fernandes,Manchester Utd,0.25,0.14,Saved,15.0,Right Foot,NaN,Casemiro,Pass (Live),NaN,NaN
6,34,Bruno Fernandes,Manchester Utd,0.69,0.59,Saved,10.0,Right Foot,NaN,Casemiro,Pass (Live),Mason Mount,Pass (Live)
7,37,Casemiro,Manchester Utd,0.07,0.00,Off Target,5.0,Head,NaN,Amad Diallo,Pass (Dead),NaN,NaN
8,42,Casemiro,Manchester Utd,0.05,0.00,Off Target,22.0,Right Foot,Volley,Diogo Dalot,Pass (Live),Lisandro Martínez,Pass (Live)
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,48,Alex Iwobi,Fulham,0.04,0.00,Off Target,7.0,Head,NaN,Andreas Pereira,Pass (Dead),NaN,NaN
11,50,Kenny Tete,Fulham,0.07,0.00,Off Target,6.0,Head,NaN,Andreas Pereira,Pass (Dead),Andreas Pereira,Pass (Live)
12,53,Mason Mount,Manchester Utd,0.30,0.30,Saved,8.0,Left Foot,NaN,Bruno Fernandes,Pass (Live),André Onana,Pass (Live)
13,55,Bruno Fernandes,Manchester Utd,0.05,0.00,Blocked,25.0,Right Foot,NaN,NaN,NaN,NaN,NaN
14,56,Kobbie Mainoo,Manchester Utd,0.03,0.00,Off Target,26.0,Right Foot,NaN,Mason Mount,Pass (Live),Casemiro,Pass (Live)
15,62,Rodrigo Muniz,Fulham,0.06,0.63,Saved,16.0,Right Foot,"Deflected, Volley",Adama Traoré,Pass (Live),Andreas Pereira,Pass (Live)
16,66,Bruno Fernandes,Manchester Utd,0.05,0.00,Blocked,26.0,Left Foot,NaN,Casemiro,Pass (Live),Alejandro Garnacho,Pass (Live)
17,69,Alejandro Garnacho,Manchester Utd,0.02,0.00,Saved off Target,24.0,Right Foot,NaN,Harry Maguire,Pass (Live),Lisandro Martínez,Pass (Live)
18,71,Adama Traoré,Fulham,0.04,0.00,Blocked,22.0,Right Foot,NaN,Tom Cairney,Pass (Live),Adama Traoré,Pass (Live)
19,72,Adama Traoré,Fulham,0.04,0.00,Blocked,26.0,Right Foot,NaN,Andreas Pereira,Pass (Live),Adama Traoré,Pass (Live)
20,76,Calvin Bassey,Fulham,0.04,0.00,Blocked,20.0,Left Foot,Volley,Calvin Bassey,Pass (Live),Andreas Pereira,Pass (Dead)
21,80,Bruno Fernandes,Manchester Utd,0.13,0.18,Saved,21.0,Right Foot,NaN,Alejandro Garnacho,Pass (Live),Joshua Zirkzee,Pass (Live)
22,87,Joshua Zirkzee,Manchester Utd,0.07,0.86,Goal,11.0,Left Foot,Volley,Alejandro Garnacho,Pass (Live),Casemiro,Pass (Live)
23,90+1,Calvin Bassey,Fulham,0.05,0.00,Off Target,10.0,Head,NaN,Andreas Pereira,Pass (Dead),Kenny Tete,Fouled
24,90+4,Alejandro Garnacho,Manchester Utd,0.67,0.00,Off Target,15.0,Left Foot,NaN,Marcus Rashford,Pass (Live),Bruno Fernandes,Pass (Live)

In [ ]:
def process_match_data(dfs):
    match_stat_df=process_match_stat_df(dfs[2])
    home_player_stat_df=[process_player_stat_df(df) for df in dfs[3:9].set_index('player').sort_index()]
    home_player_stat_df=pd.concat(home_player_stat_df)
    away_player_stat_df=[process_player_stat_df(df) for df in dfs[10:16].set_index('player').sort_index()]
    away_player_stat_df=pd.concat(away_player_stat_df)